// flow-typed signature: 2a4f8c7c649979dd5bcb9e5a1a9c7bc6
// flow-typed version: <<STUB>>/eslint-plugin-standard_v^2.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-standard/rules/array-bracket-even-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-standard/rules/computed-property-even-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-standard/rules/object-curly-even-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-standard/tests/array-bracket-even-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-standard/tests/computed-property-even-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-standard/tests/object-curly-even-spacing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-standard/index' {
  declare module.exports: $Exports<'eslint-plugin-standard'>;
}
declare module 'eslint-plugin-standard/index.js' {
  declare module.exports: $Exports<'eslint-plugin-standard'>;
}
declare module 'eslint-plugin-standard/rules/array-bracket-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/rules/array-bracket-even-spacing'>;
}
declare module 'eslint-plugin-standard/rules/computed-property-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/rules/computed-property-even-spacing'>;
}
declare module 'eslint-plugin-standard/rules/object-curly-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/rules/object-curly-even-spacing'>;
}
declare module 'eslint-plugin-standard/tests/array-bracket-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/tests/array-bracket-even-spacing'>;
}
declare module 'eslint-plugin-standard/tests/computed-property-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/tests/computed-property-even-spacing'>;
}
declare module 'eslint-plugin-standard/tests/object-curly-even-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-standard/tests/object-curly-even-spacing'>;
}
