// flow-typed signature: 5aab23458746576e02c1f33f3df78fb4
// flow-typed version: <<STUB>>/normalize.css_v^5.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
